USE [master]
GO

/****** Object:  Database [Aerolineas]    Script Date: 8/10/2018 12:17:22 ******/
CREATE DATABASE [Aerolineas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Aerolineas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Aerolineas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Aerolineas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Aerolineas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Aerolineas] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Aerolineas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Aerolineas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Aerolineas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Aerolineas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Aerolineas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Aerolineas] SET ARITHABORT OFF 
GO

ALTER DATABASE [Aerolineas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Aerolineas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Aerolineas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Aerolineas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Aerolineas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Aerolineas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Aerolineas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Aerolineas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Aerolineas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Aerolineas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Aerolineas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Aerolineas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Aerolineas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Aerolineas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Aerolineas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Aerolineas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Aerolineas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Aerolineas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Aerolineas] SET  MULTI_USER 
GO

ALTER DATABASE [Aerolineas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Aerolineas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Aerolineas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Aerolineas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Aerolineas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Aerolineas] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Aerolineas] SET  READ_WRITE 
GO

